# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        # TODO: test all relevant versions
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade virtualenv
        python -m virtualenv venv
        source ./venv/bin/activate
        python -m pip install --upgrade pip
        python setup.py install
        python -m pip freeze
    - name: Lint with flake8
      run: |
        python -m pip install flake8
        python -m flake8 setup.py pykusto test --count --max-complexity=10 --max-line-length=180 --show-source --statistics
    - name: Test with pytest
      run: |
        python -m pip install pytest pytest-cov
        python -m pip freeze
        python -m pip show azure-kusto-data
        python -m pip show azure-core
        python -m pip show pytest
        python -m pip show pykusto
        python -m pytest --cov=pykusto --cov-report term-missing --cov-fail-under=100
